/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.HeadlessException;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class vista_1 extends javax.swing.JFrame {

    /**
     * Creates new form pedidos
     */
    public vista_1() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distribuidorFarmaceutico = new javax.swing.ButtonGroup();
        nombreMedicamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tipoMedicamento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidadMedicamento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        farmaciaPrincipal = new javax.swing.JCheckBox();
        farmaciaSecundaria = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        confirmarPedido = new javax.swing.JButton();
        borrarPedido = new javax.swing.JButton();
        rb_cemefar = new javax.swing.JRadioButton();
        rb_empsephar = new javax.swing.JRadioButton();
        rb_cofarma = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        distribuidorFarmaceutico.add(rb_cemefar);
        distribuidorFarmaceutico.add(rb_empsephar);
        distribuidorFarmaceutico.add(rb_cofarma);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Pedidos de Medicamentos");
        setBackground(new java.awt.Color(121, 146, 255));

        nombreMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMedicamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del Medicamento:");

        tipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));
        tipoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMedicamentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo del Medicamento:");

        jLabel3.setText("Cantidad del Medicamento:");

        cantidadMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMedicamentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Distribuidor Farmacéutico:");

        farmaciaPrincipal.setText("Principal");
        farmaciaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farmaciaPrincipalActionPerformed(evt);
            }
        });

        farmaciaSecundaria.setText("Secundaria");
        farmaciaSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farmaciaSecundariaActionPerformed(evt);
            }
        });

        jLabel5.setText("Sucursal Farmaceutica:");

        confirmarPedido.setText("Confirmar");
        confirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarPedidoActionPerformed(evt);
            }
        });

        borrarPedido.setText("Borrar");
        borrarPedido.setMaximumSize(new java.awt.Dimension(84, 22));
        borrarPedido.setMinimumSize(new java.awt.Dimension(84, 22));
        borrarPedido.setPreferredSize(new java.awt.Dimension(84, 22));
        borrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarPedidoActionPerformed(evt);
            }
        });

        rb_cemefar.setText("Cemefar");
        rb_cemefar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cemefarActionPerformed(evt);
            }
        });

        rb_empsephar.setText("Empsephar");
        rb_empsephar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_empsepharActionPerformed(evt);
            }
        });

        rb_cofarma.setText("Cofarma");
        rb_cofarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cofarmaActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pedido de Medicamentos");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setText("Por favor realice el pedido del medicamento segun lo solicitado a continuacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cantidadMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_cofarma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_empsephar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_cemefar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(confirmarPedido)
                                            .addComponent(farmaciaPrincipal))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(farmaciaSecundaria)
                                            .addComponent(borrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)
                                .addComponent(nombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addComponent(tipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_cofarma)
                    .addComponent(rb_empsephar)
                    .addComponent(rb_cemefar))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farmaciaPrincipal)
                    .addComponent(farmaciaSecundaria)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarPedido)
                    .addComponent(borrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMedicamentoActionPerformed

    private void tipoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMedicamentoActionPerformed

    private void cantidadMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMedicamentoActionPerformed

    private void farmaciaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farmaciaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_farmaciaPrincipalActionPerformed

    private void farmaciaSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farmaciaSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_farmaciaSecundariaActionPerformed

    private void confirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarPedidoActionPerformed

    private void borrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarPedidoActionPerformed

    private void rb_cemefarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cemefarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_cemefarActionPerformed

    private void rb_cofarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cofarmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_cofarmaActionPerformed

    private void rb_empsepharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_empsepharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_empsepharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton borrarPedido;
    public javax.swing.JTextField cantidadMedicamento;
    public javax.swing.JButton confirmarPedido;
    public javax.swing.ButtonGroup distribuidorFarmaceutico;
    public javax.swing.JCheckBox farmaciaPrincipal;
    public javax.swing.JCheckBox farmaciaSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField nombreMedicamento;
    public javax.swing.JRadioButton rb_cemefar;
    public javax.swing.JRadioButton rb_cofarma;
    public javax.swing.JRadioButton rb_empsephar;
    public javax.swing.JComboBox<String> tipoMedicamento;
    // End of variables declaration//GEN-END:variables
}
